let chatUser=null,chatRoomId=null,chatType='internal',chatPlatform='portal',chatLastMax=0;
const chatEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chatFmt=s=>s?new Date(s.replace(' ','T')+'Z').toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'';
const chatInitials=s=>(s||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('');
function renderOnline(list){const el=document.getElementById('onlineUsers');if(!el)return;el.innerHTML=(list||[]).map(x=>`<span class="chat-online-chip" title="${chatEsc(x.platform==='emulti'?'eMulti':'Portal Saúde')}"><i></i>${chatEsc(x.name||x.username)}</span>`).join('')||'<span class="muted">Nenhum usuário online agora.</span>';}
function renderMessages(d){const box=document.getElementById('messages');const msgs=d.messages||[];box.innerHTML=msgs.map(m=>`<div class="chat-message-row ${m.user_id===chatUser.id?'is-own':''}"><div class="chat-avatar">${chatEsc(chatInitials(m.name||m.username))}</div><div class="chat-message ${m.user_id===chatUser.id?'is-own':''}"><div class="chat-message__meta"><strong>${chatEsc(m.name||m.username)}</strong><span>${chatEsc(m.platform==='emulti'?'eMulti':'Portal')}</span><span>${chatEsc(chatFmt(m.created_at))}</span></div><div>${chatEsc(m.body).replace(/\n/g,'<br>')}</div></div></div>`).join('')||'<div class="empty-state">Nenhuma mensagem ainda.</div>';const max=msgs.length?Math.max(...msgs.map(x=>Number(x.id||0))):0;if(max!==chatLastMax){box.scrollTop=box.scrollHeight;chatLastMax=max;}renderOnline(d.online);const status=document.getElementById('supportStatus');if(status&&chatType==='support')status.textContent=d.room_status==='closed'?'Encerrado':'Em atendimento';}
async function loadMessages(){const q=new URLSearchParams({type:chatType,platform:chatPlatform});if(chatRoomId&&chatType==='support')q.set('room_id',chatRoomId);const r=await fetch('/api/chat/messages?'+q,{credentials:'same-origin'});const d=await r.json();if(!r.ok)return;chatRoomId=d.room_id;renderMessages(d);document.getElementById('ticketBtn')?.toggleAttribute('hidden',chatType!=='support');if(chatUser.role==='super_admin'&&chatType==='support')await loadRooms();}
async function sendChat(){const el=document.getElementById('text');const body=el.value.trim();if(!body)return;const btn=document.getElementById('sendBtn');btn.disabled=true;const r=await fetch('/api/chat/messages',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({type:chatType,room_id:chatRoomId,body,platform:chatPlatform})});const d=await r.json().catch(()=>({}));btn.disabled=false;if(r.ok){el.value='';await loadMessages();}else alert(d.error||'Não foi possível enviar a mensagem.');}
async function openTicket(){const title=prompt('Título do chamado:','Problema identificado no suporte');if(!title)return;const description=prompt('Resumo do problema (opcional):','')||'';const r=await fetch('/api/chamados',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({title,description,source_room_id:chatRoomId,platform:chatPlatform})});const d=await r.json();alert(r.ok?`Chamado ${d.codigo} aberto.`:(d.error||'Erro ao abrir chamado.'));}
async function toggleRoom(action){if(!chatRoomId)return;const r=await fetch('/api/chat/support-rooms',{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({room_id:chatRoomId,action})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível atualizar o atendimento.');await loadRooms();await loadMessages();}
async function loadRooms(){const d=await (await fetch('/api/chat/support-rooms',{credentials:'same-origin'})).json();if(!chatRoomId&&d.rooms?.length)chatRoomId=Number(d.rooms[0].id);const list=document.getElementById('roomList');if(!list)return;list.innerHTML=(d.rooms||[]).map(r=>`<button class="chat-room-btn ${Number(r.id)===Number(chatRoomId)?'is-active':''}" data-room="${r.id}" data-status="${r.status}"><span class="chat-room-title"><i class="presence-dot ${r.is_online?'is-online':''}"></i><strong>${chatEsc(r.name||r.username)}</strong>${Number(r.unread_count||0)>0?`<b class="chat-unread">${r.unread_count}</b>`:''}</span><small>${chatEsc(r.last_message||'Sem mensagens')}</small><em>${r.status==='closed'?'Encerrado':'Aberto'}</em></button>`).join('')||'<div class="muted">Nenhum atendimento.</div>';document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{chatRoomId=Number(b.dataset.room);document.querySelectorAll('[data-room]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const close=document.getElementById('closeSupportBtn'),reopen=document.getElementById('reopenSupportBtn');if(close)close.hidden=b.dataset.status==='closed';if(reopen)reopen.hidden=b.dataset.status!=='closed';loadMessages();});}
async function initChatPage(){chatUser=await initPortalChrome();if(!chatUser)return;chatType=document.body.dataset.chatType||'internal';chatPlatform=document.body.dataset.platform||'portal';const cfg=(await (await fetch('/api/chat/config')).json()).config||{};document.getElementById('retention').textContent=`As mensagens deste chat são mantidas por ${cfg[chatType==='support'?'support_retention_days':'internal_retention_days']||30} dias.`;if(chatType==='support'&&chatUser.role==='super_admin'){document.getElementById('rooms').hidden=false;document.getElementById('supportAdminActions').hidden=false;await loadRooms();}await loadMessages();setInterval(loadMessages,5000);setInterval(()=>fetch('/api/chat/status?platform='+chatPlatform,{credentials:'same-origin'}).catch(()=>{}),20000);}
document.getElementById('sendBtn')?.addEventListener('click',sendChat);document.getElementById('text')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat();}});document.getElementById('ticketBtn')?.addEventListener('click',openTicket);document.getElementById('closeSupportBtn')?.addEventListener('click',()=>toggleRoom('close'));document.getElementById('reopenSupportBtn')?.addEventListener('click',()=>toggleRoom('reopen'));initChatPage();
